/*
PERGUNTAS:
1 -> Qual departamento com maior número de pessoas?
2 -> Quais são os departamentos por cidade?
3 -> Relação de empregados por departamento
*/


/*
PERGUNTA 1:
RETORNANDO APENAS O PRIMEIRO DEPARTAMENTO (COM MAIOR NÚMERO DE PESSOAS)
COMO NÃO É UMA BUSCA EXATA, E SIM TEMOS UM AGRUPAMENTO PARA DESOBRIR O MAIOR, O MELHOR TIPO DE INDICE SERIA O BTREE
COMO JÁ TEMOS UM ÍNDICE NA CHAVE PRIMÁRIA DNUMBER, O IDEAL PARA ESSA BUSCA É CRIAR UM OUTRO NA CHAVE DNO DA TABELA EMPLOYEE
*/
select count(*) AS QTD_PESSOAS, Dname AS NOME_DEPT from employee inner join department on Dno = Dnumber group by Dname order by QTD_PESSOAS DESC LIMIT 1;

CREATE INDEX idx_employee_dno ON employee(DNO) USING BTREE;


/*
PERGUNTA 2:
USANDO UM ÍNDICE EM DNAME E DLOCATION PODE AUXILIAR NO AGRUPAMENTO FINAL, PORÉM COMO É AGRUPAMENTO E NÃO UMA BUSCA EXATA O MELHOR TIPO SERIA BTREE
UM ÍNDICE COMPOSTO EM DNUMBER E DLOCATION PODE AUXILIAR, JÁ QUE SÃO USADOS PARA JUNÇÃO E AGRUPAMENTO NA MESMA TABELA
*/

SELECT DL.DLOCATION, D.DNAME, COUNT(*) AS QTD_DEPARTAMENTOS FROM DEPARTMENT D INNER JOIN DEPT_LOCATIONS DL ON D.DNUMBER = DL.DNUMBER GROUP BY DL.DLOCATION, D.DNAME;

CREATE INDEX idx_dept_locations_dlocation ON DEPT_LOCATIONS (DLOCATION) USING BTREE;
CREATE INDEX idx_dept_dname ON DEPARTMENT (DNAME) USING BTREE;
CREATE INDEX idx_dept_locations_dnumber_dlocation ON DEPT_LOCATIONS (DNUMBER, DLOCATION) USING BTREE;

/*
PERGUNTA 3:
COMO JÁ CRIAMOS UM ÍNDICE EM DNO ANTERIORMENTE, ESSE NÃO SERÁ MAIS NECESSÁRIO
COMO JÁ TEMOS TAMBÉM UM ÍNDICE CRIADO EM DNUMBER POR SER UMA PRIMARY KEY, NÃO É NECESSÁRIO TAMBÉM CRIAR OUTRO TIPO DE ÍNDICE
*/

select CONCAT(Fname, " ", Minit, " ", Lname), Dname AS NOME_DEPT from employee inner join department on Dno = Dnumber;

