/*
CODE 1 - CRIANDO TRANSAÇÕES DE CONSULTAS E MODIFICAÇÕES, DEFININDO TAMBÉM NÍVEIS DE ISOLAMENTO 

NÍVEIS DE ISOLAMENTO:
READ UNCOMMITTED -> PERMITE LEITURA DE DADOS NÃO CONFIRMADOS 
READ COMMITTED -> LEITURA SOMENTE DE DADOS CONFIRMADOS, PORÉM NÃO EVITA LEITURA NÃO REPETÍVEL
REPEATABLE READ -> LEITURA DE DADOS CONFIRMADOS E GARANTE LEITURA NÃO REPETÍVEL
SERIALIZABLE -> LEITURA DE DADOS CONFIRMADOS, GARANTE LEITURA NÃO REPETÍVEL E BLOQUEIA PARA ESCRITA (NÍVEL MAIS RESTRITO)
*/

SET @@autocommit = 0;


-- TRANSACAO 1 -> LENDO DADOS ECOMMERCE
START transaction;
SET SESSION TRANSACTION ISOLATION LEVEL read committed; -- COMO APENAS EXECUTA UMA LEITURA O NÍVEL DE ISOLAMENTO READ COMMITTED JÁ É SUFICIENTE POIS LE APENAS OS DADOS QUE JA FORAM CONFIRMADOS
USE ecommerce;
SELECT idPedido, nome_completo as nome_cliente,descricao FROM CLIENTE inner join pedido on idCliente = Cliente_idCliente;
COMMIT; -- ENCERRA A TRANSAÇÃO, MESMO QUE SEJA SOMENTE LEITURA


-- TRANSACAO 2 -> ALTERANDO DADOS ECOMMERCE
START transaction;
SET SESSION TRANSACTION ISOLATION LEVEL repeatable read; -- O NÍVEL REPEATABLE READ GARANTIRÁ QUE SÓ FARA A LEITURA DOS DADOS JÁ CONFIRMADOS E NÃO TENHA NENHUMA LEITURA REPETIVEL 
USE ecommerce;
LOCK TABLES PRODUTO WRITE; -- TRAVANDO A TABELA PARA ATUALIZAR PREÇO
UPDATE PRODUTO SET VALOR = 5300 WHERE idProduto = 1;
UNLOCK TABLES; -- DESBLOQUEANDO A TABELA PARA PERMITIR QUE OUTRAS TRANSAÇÕES ACESSEM
select * from produto; 
COMMIT; -- ENCERRA A TRANSAÇÃO ALTERANDO EM DEFINITIVO O VALOR


-- TRANSACAO 3 -> DELETANDO DADOS ECOMMERCE
START transaction;
SET SESSION TRANSACTION ISOLATION LEVEL repeatable read; -- GARANTE QUE NÃO IRÁ DELETAR ALGO QUE FOI MODIFICADO DURANTE A TRANSAÇÃO ( EVITA LEITURA NÃO REPETIVEL)
USE ecommerce;
LOCK TABLES PRODUTO WRITE; -- TRAVANDO A TABELA PARA GARANTIR QUE NINGUEM ACESSE O PRODUTO ENQUANTO ESTÁ DELETANDO, PODERIA TAMBÉM SER UTILIZADO O NÍVEL SERIALIZABLE PARA TRAVAR A TABELA
DELETE FROM PRODUTO WHERE idProduto = 6;
UNLOCK TABLES; -- DESBLOQUEANDO A TABELA PARA PERMITIR QUE OUTRAS TRANSAÇÕES ACESSEM
select * from produto; 
COMMIT; -- ENCERRA A TRANSAÇÃO EXCLUINDO EM DEFINITIVO O PRODUTO


-- TRANSACAO 3 -> INSERINDO DADOS ECOMMERCE
START transaction;
SET SESSION TRANSACTION ISOLATION LEVEL repeatable read; -- GARANTE QUE NÃO IRÁ INSERIR UM PRODUTO QUE JÁ EXISTA
USE ecommerce;
SET @novo_valor := (SELECT max(idProduto)+1 from produto);
INSERT INTO PRODUTO VALUES (@novo_valor, 'Computador', 'PC Gamer', 6100);
select * from produto;
COMMIT; -- ENCERRA A TRANSAÇÃO INSERINDO EM DEFINITIVO O NOVO PRODUTO
